name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # تحديث يومي
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: ibrahim-sisar
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
